services:
  snapp:
    image: uraniadev/snapp:0.9-rc
    ports:
      - 3000:3000
    environment:
      DATABASE_PROVIDER: sqlite # mysql | postgres
      DATABASE_URL: file:./db.sqlite
      # DATABASE_URL: postgres://root:password@postgres:5432/snapp
      # DATABASE_URL: mysql://root:password@mariadb:3306/snapp
  # mariadb:
  #   image: mariadb:latest
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: snapp
  #   volumes:
  #     - ../sql:/var/lib/mysql
  #   healthcheck:
  #     test: ['CMD', 'healthcheck.sh', '--su-mysql', '--connect', '--innodb_initialized']
  #     start_period: 1m
  #     start_interval: 10s
  #     interval: 1m
  #     timeout: 5s
  #     retries: 3
  # postgres:
  #   image: postgres:17.4-alpine
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ../postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_USER=root
  #     - POSTGRES_DB=snapp
 
