services:
  snapp:
    image: uraniadev/snapp:latest
    ports:
      - 3000:3000
    environment:
      DATABASE_MYSQL_URL: "mysql://root:password@mariadb:3306/snappdb"
      TOKEN_SECRET: # openssl rand -base64 32
      ORIGIN: https://example.com
      DATABASE_PROVIDER: mysql
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - snapp

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: snappdb
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - snapp
    healthcheck:
      test: [
        "CMD",
        "healthcheck.sh",
        "--su-mysql",
        "--connect",
        "--innodb_initialized",
      ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
networks:
  snapp:
    external: false

volumes:
  mariadb-data:
