<script lang="ts">
	import { Button, Container, Heading, Image, Paragraph } from '@uraniadev/emailer';
	import { env } from '$env/dynamic/public';

	const { appname, recoveryURL }: { appname: string; recoveryURL: string } =
		$props();
</script>

<Container>
	<Button class="p-0" href={env.PUBLIC_URL}
		><Image
			class="flex max-w-[64px] items-center rounded-sm pe-4"
			width="64px"
			src="{env.PUBLIC_URL}/logo.svg"
		/></Button
	>
	<Heading class="text-blue" level={2}>{appname}</Heading>
	<Paragraph>You receive this email because you are invited to use our app.</Paragraph>
	<Paragraph>If you think this is a mistake please notice the platform administrator.</Paragraph>

	<Button class="mt-4 max-w-max rounded bg-neutral-800 !text-white" href={recoveryURL}
		>Complete your profile</Button
	>
	<Paragraph class="mt-8 text-center text-sm"
		>This is an autogenerated message, do not reply to this email.</Paragraph
	>
</Container>
