<script lang="ts">
	import { Button, Container, Heading, Image, inline, Paragraph } from "@uraniadev/emailer";
	import { env } from "$env/dynamic/public";

	const { appname, ip, recoveryURL }: { appname: string; ip: string; recoveryURL: string } =
		$props();
</script>

<Container>
	<Button class="p-0" href={env.PUBLIC_URL}
		><Image
			class="flex max-w-[64px] items-center rounded-sm pe-4"
			width="64px"
			src="{env.PUBLIC_URL}/logo.png"
		/></Button
	>
	<Heading class="text-blue" level={2}>{appname}</Heading>
	<Paragraph>You requested to recover your password.</Paragraph>
	<Paragraph>If you think this is a mistake please notice the platform administrator.</Paragraph>

	<table style={inline("w-full")}>
		<tbody>
			<tr style={inline("even:bg-neutral-300/50 m-0 border-t p-0")}>
				<td style={inline("border p-1 w-max	 text-left")}>
					<Paragraph class="font-code text-sm">{ip}</Paragraph>
				</td>
				<td style={inline("border p-1 w-max text-left")}>
					<Paragraph class="font-code whitespace-nowrap text-sm"
						>{new Date().toUTCString()}</Paragraph
					>
				</td>
				<td style={inline("border p-1 w-full text-left")}>
					<Paragraph class="font-code text-sm">Password Recovery requested.</Paragraph>
				</td>
			</tr>
		</tbody>
	</table>
	<Button class="mt-4 max-w-max rounded bg-neutral-800 !text-white" href={recoveryURL}
		>Reset password</Button
	>
	<Paragraph class="mt-8 text-center text-sm"
		>This is an autogenerated message, do not reply to this email.</Paragraph
	>
</Container>
