<script lang="ts">
	import { Button, Container, Heading, Image, inline, Paragraph } from '@uraniadev/emailer';
	import { env } from '$env/dynamic/public';

	const { appname, ip }: { appname: string; ip: string } = $props();
</script>

<Container>
	<Button class="p-0" href={env.PUBLIC_URL}
		><Image
			class="flex max-w-[64px] items-center rounded-sm pe-4"
			width="64px"
			src="{env.PUBLIC_URL}/logo.png"
		/></Button
	>
	<Heading class="text-blue" level={2}>{appname}</Heading>
	<Paragraph>You changed your password.</Paragraph>
	<Paragraph
		>If you <b>have not</b> done this action on your profile notice the platform administrator right
		away as your profile could have been breached.</Paragraph
	>

	<table style={inline('w-full')}>
		<tbody>
			<tr style={inline('even:bg-neutral-300/50 m-0 border-t p-0')}>
				<td style={inline('border p-1 w-max	 text-left')}>
					<Paragraph class="font-code text-sm">{ip}</Paragraph>
				</td>
				<td style={inline('border p-1 w-max text-left')}>
					<Paragraph class="font-code whitespace-nowrap text-sm"
						>{new Date().toUTCString()}</Paragraph
					>
				</td>
				<td style={inline('border p-1 w-full text-left')}>
					<Paragraph class="font-code text-sm">Password updated.</Paragraph>
				</td>
			</tr>
		</tbody>
	</table>

	<Paragraph class="mt-8 text-center text-sm"
		>This is an autogenerated message, do not reply to this email.</Paragraph
	>
</Container>
