<script lang="ts">
	import { Button, Container, Heading, Image, Paragraph } from '@uraniadev/emailer';
	import { env } from '$env/dynamic/public';

	const { appname, cta, name }: { appname: string; cta: string; name: string } = $props();
</script>

<Container>
	<Button class="p-0" href={env.PUBLIC_URL}
		><Image
			class="flex max-w-[64px] items-center rounded-sm pe-4"
			width="64px"
			src="{env.PUBLIC_URL}/logo.png"
		/></Button
	>
	<Heading class="text-blue" level={2}>{appname}</Heading>
	<Paragraph>
		Hello {name}
	</Paragraph>
	<Paragraph>
		Welcome to {appname}, a simple and self hosted url shortner. You received this email because you
		registered to our platform
	</Paragraph>
	<Button class="mt-4 max-w-max rounded bg-neutral-800 text-white" href={cta}>Open Dashboard</Button
	>
	<Paragraph class="mt-8 text-center text-sm"
		>This is an autogenerated message, do not reply to this email.</Paragraph
	>
</Container>
