<script lang="ts">
	import { Button, Container, Heading, Image, inline, Paragraph } from '@uraniadev/emailer';
	import { env } from '$env/dynamic/public';

	const { appname, cta, ip, name }: { appname: string; cta: string; ip: string; name: string } =
		$props();
</script>

<Container>
	<Button class="p-0" href={env.PUBLIC_URL}
		><Image
			class="flex max-w-[64px] items-center rounded-sm pe-4"
			width="64px"
			src="{env.PUBLIC_URL}/logo.png"
		/></Button
	>
	<Heading class="text-blue" level={2}>{appname}</Heading>
	<Paragraph>
		Hello {name}
	</Paragraph>
	<Paragraph>
		Welcome to {appname}, a simple and self hosted url shortner. You received this email because you
		registered to our platform, and yet have to verify your account.
	</Paragraph>
	<Button class="mt-4 max-w-max rounded bg-neutral-800 text-white" href={cta}>Verify email</Button>
	<table style={inline('w-full mt-8')}>
		<tbody>
			<tr style={inline('even:bg-neutral-300/50 m-0 border-t p-0')}>
				<td style={inline('border p-1 w-max	 text-left')}>
					<Paragraph class="font-code text-sm">{ip}</Paragraph>
				</td>
				<td style={inline('border p-1 w-max text-left')}>
					<Paragraph class="font-code whitespace-nowrap text-sm"
						>{new Date().toUTCString()}</Paragraph
					>
				</td>
				<td style={inline('border p-1 w-full text-left')}>
					<Paragraph class="font-code text-sm">Password Recovery requested.</Paragraph>
				</td>
			</tr>
		</tbody>
	</table>
	<Paragraph class="mt-8 text-center text-sm"
		>This is an autogenerated message, do not reply to this email.</Paragraph
	>
</Container>
